name = "GLNS"
uuid = "516e1c79-eeb0-43d2-9daf-3648d985e5d9"
authors = ["Stephen L. Smith <stephen.smith@uwaterloo.ca>, Frank Imeson"]
version = "1.0.0"

[deps]
CPUTime = "a9c8d775-2e2e-55fc-8582-045d282d599e"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ThreadPinning = "811555cd-349b-4f26-b7bc-1f208b848042"

[compat]
CPUTime = "1.0.0"
NPZ = "0.4.3"
Printf = "1.11.0"
Sockets = "1.11.0"
ThreadPinning = "1.0.2"
julia = "1.0"
